<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Pocket01DataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now_date = date('Y-m-d h:i:s');

        // 1.寶可夢世代分類
        DB::table('pocket_generations')->truncate();
        DB::table('pocket_generations')->insert([
            [
                'id' => 1,
                'name' => '第一世代',
                'start' => '1996年02月',
                'end' => '1999年10月',
                'pocket_count' => 151,
                'area' => '關都地區',
                'sort' => 1,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 2,
                'name' => '第二世代',
                'start' => '1999年11月',
                'end' => '2002年10月',
                'pocket_count' => 251,
                'area' => '城都地區',
                'sort' => 2,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 3,
                'name' => '第三世代',
                'start' => '2002年11月',
                'end' => '2006年08月',
                'pocket_count' => 386,
                'area' => '豐緣地區',
                'sort' => 3,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 4,
                'name' => '第四世代',
                'start' => '2006年09月',
                'end' => '2010年08月',
                'pocket_count' => 493,
                'area' => '神奧地區',
                'sort' => 4,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 5,
                'name' => '第五世代',
                'start' => '2010年09月',
                'end' => '2013年09月',
                'pocket_count' => 649,
                'area' => '合眾地區',
                'sort' => 5,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 6,
                'name' => '第六世代',
                'start' => '2013年10月',
                'end' => '2016年10月',
                'pocket_count' => 721,
                'area' => '卡洛斯地區',
                'sort' => 6,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 7,
                'name' => '第七世代',
                'start' => '2016年11月',
                'end' => '2019年10月',
                'pocket_count' => 809,
                'area' => '阿羅拉地區',
                'sort' => 7,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 8,
                'name' => '第八世代',
                'start' => '2019年11月',
                'end' => '',
                'pocket_count' => 898,
                'area' => '伽勒爾地區',
                'sort' => 8,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
        ]);

        // 2.寶可夢遊戲
        DB::table('pocket_games')->truncate();
        DB::table('pocket_games')->insert([
            [
                'id' => 1,
                'pg_id' => 1,
                'name' => '寶可夢 紅',
                'name_jp' => 'ポケットモンスター 赤',
                'description' => '1996年2月27日發售，2016年2月27日重新在Nintendo 3DS中的Virtual Console發售。',
                'sort' => 1,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 2,
                'pg_id' => 1,
                'name' => '寶可夢 綠',
                'name_jp' => 'ポケットモンスター 緑',
                'description' => '1996年2月27日發售，2016年2月27日重新在Nintendo 3DS中的Virtual Console發售。（歐美地區以藍版替代綠版而沒有發行日本的綠版）。',
                'sort' => 2,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 3,
                'pg_id' => 1,
                'name' => '寶可夢 藍',
                'name_jp' => 'ポケットモンスター 青',
                'description' => '1996年10月15日首次於日本地區限量推出，1999年10月10日全面發售，2016年2月27日重新在Nintendo 3DS中的Virtual Console發售。',
                'sort' => 3,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 4,
                'pg_id' => 1,
                'name' => '寶可夢 皮卡丘',
                'name_jp' => 'ポケットモンスター ピカチュウ',
                'description' => '又稱黃版，1998年9月12日發售，2016年2月27日重新在Nintendo 3DS中的Virtual Console發售。',
                'sort' => 4,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],

            [
                'id' => 5,
                'pg_id' => 2,
                'name' => '寶可夢 金',
                'name_jp' => 'ポケットモンスター 金',
                'description' => '1999年11月21日發售，2017年9月22日重新在Nintendo 3DS中的Virtual Console發售。',
                'sort' => 5,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 6,
                'pg_id' => 2,
                'name' => '寶可夢 銀',
                'name_jp' => 'ポケットモンスター 銀',
                'description' => '1999年11月21日發售，2017年9月22日重新在Nintendo 3DS中的Virtual Console發售。',
                'sort' => 6,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 7,
                'pg_id' => 2,
                'name' => '寶可夢 水晶',
                'name_jp' => 'ポケットモンスター クリスタルバージョン',
                'description' => '2000年12月14日發售，2018年1月26日重新在Nintendo 3DS中的Virtual Console發售。',
                'sort' => 7,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],

            [
                'id' => 8,
                'pg_id' => 3,
                'name' => '寶可夢 紅寶石',
                'name_jp' => 'ポケットモンスター ルビー',
                'description' => '2002年11月21日發售。',
                'sort' => 8,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 9,
                'pg_id' => 3,
                'name' => '寶可夢 藍寶石',
                'name_jp' => 'ポケットモンスター サファイア',
                'description' => '2002年11月21日發售。',
                'sort' => 9,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 10,
                'pg_id' => 3,
                'name' => '寶可夢 火紅',
                'name_jp' => 'ポケットモンスター ファイアレッド',
                'description' => '為紅版的重製作，2004年1月29日發售。',
                'sort' => 10,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 11,
                'pg_id' => 3,
                'name' => '寶可夢 葉綠',
                'name_jp' => 'ポケットモンスター リーフグリーン',
                'description' => '為綠版的重製作，2004年1月29日發售。',
                'sort' => 11,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 12,
                'pg_id' => 3,
                'name' => '寶可夢 綠寶石',
                'name_jp' => 'ポケットモンスター エメラルド',
                'description' => '2004年9月16日發售。',
                'sort' => 12,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],

            [
                'id' => 13,
                'pg_id' => 4,
                'name' => '寶可夢 鑽石',
                'name_jp' => 'ポケットモンスター ダイヤモンド',
                'description' => '2006年9月28日發售。',
                'sort' => 13,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 14,
                'pg_id' => 4,
                'name' => '寶可夢 珍珠',
                'name_jp' => 'ポケットモンスター パール',
                'description' => '2006年9月28日發售。',
                'sort' => 14,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 15,
                'pg_id' => 4,
                'name' => '寶可夢 白金',
                'name_jp' => 'ポケットモンスター プラチナ',
                'description' => '2008年9月13日發售。',
                'sort' => 15,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 16,
                'pg_id' => 4,
                'name' => '寶可夢 心金',
                'name_jp' => 'ポケットモンスター ハートゴールド',
                'description' => '為金版的重製作，2009年9月12日發售。',
                'sort' => 16,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 17,
                'pg_id' => 4,
                'name' => '寶可夢 魂銀',
                'name_jp' => 'ポケットモンスター ソウルシルバー',
                'description' => '為銀版的重製作，2009年9月12日發售。',
                'sort' => 17,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],

            [
                'id' => 18,
                'pg_id' => 5,
                'name' => '寶可夢 黑',
                'name_jp' => 'ポケットモンスター ブラック',
                'description' => '2010年9月18日發售。',
                'sort' => 18,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 19,
                'pg_id' => 5,
                'name' => '寶可夢 白',
                'name_jp' => 'ポケットモンスター ホワイト',
                'description' => '2010年9月18日發售。',
                'sort' => 19,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 20,
                'pg_id' => 5,
                'name' => '寶可夢 黑2',
                'name_jp' => 'ポケットモンスター ブラック2',
                'description' => '2012年6月23日發售。',
                'sort' => 20,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 21,
                'pg_id' => 5,
                'name' => '寶可夢 白2',
                'name_jp' => 'ポケットモンスター ホワイト2',
                'description' => '2012年6月23日發售。',
                'sort' => 21,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],

            [
                'id' => 22,
                'pg_id' => 6,
                'name' => '寶可夢 X',
                'name_jp' => 'ポケットモンスター X',
                'description' => '2013年10月12日全球同步發售發售。',
                'sort' => 22,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 23,
                'pg_id' => 6,
                'name' => '寶可夢 Y',
                'name_jp' => 'ポケットモンスター Y',
                'description' => '2013年10月12日全球同步發售發售。',
                'sort' => 23,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 24,
                'pg_id' => 6,
                'name' => '寶可夢 歐米加紅寶石',
                'name_jp' => 'ポケットモンスター オメガルビー',
                'description' => '為紅寶石版的重製作，2014年11月21日全球部分地區發售（歐洲地區為11月28日）。',
                'sort' => 24,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 25,
                'pg_id' => 6,
                'name' => '寶可夢 阿爾法藍寶石',
                'name_jp' => 'ポケットモンスター アルファサファイア',
                'description' => '為藍寶石版的重製作，2014年11月21日全球部分地區發售（歐洲地區為11月28日）。',
                'sort' => 25,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],

            [
                'id' => 26,
                'pg_id' => 7,
                'name' => '精靈寶可夢 太陽',
                'name_jp' => 'ポケットモンスター サン',
                'description' => '運行於任天堂3DS，2016年11月18日全球部分地區發售（歐洲地區為11月23日）。',
                'sort' => 26,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 27,
                'pg_id' => 7,
                'name' => '精靈寶可夢 月亮',
                'name_jp' => 'ポケットモンスター ムーン',
                'description' => '運行於任天堂3DS，2016年11月18日全球部分地區發售（歐洲地區為11月23日）。',
                'sort' => 27,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 28,
                'pg_id' => 7,
                'name' => '精靈寶可夢 究極之日',
                'name_jp' => 'ポケットモンスター ウルトラサン',
                'description' => '運行於任天堂3DS，2017年11月17日全球同步發售。',
                'sort' => 28,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 29,
                'pg_id' => 7,
                'name' => '精靈寶可夢 究極之月',
                'name_jp' => 'ポケットモンスター ウルトラムーン',
                'description' => '運行於任天堂3DS，2017年11月17日全球同步發售。',
                'sort' => 29,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 30,
                'pg_id' => 7,
                'name' => '精靈寶可夢 Let\'s Go！皮卡丘',
                'name_jp' => 'ポケットモンスター Let\'s Go! ピカチュウ',
                'description' => '為皮卡丘版添加寶可夢GO元素的重製作，2018年11月16日全球同步發售。',
                'sort' => 30,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 31,
                'pg_id' => 7,
                'name' => '精靈寶可夢 Let\'s Go！伊布',
                'name_jp' => 'ポケットモンスター Let\'s Go! イーブイ',
                'description' => '為皮卡丘版添加寶可夢GO元素的重製作，2018年11月16日全球同步發售。',
                'sort' => 31,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],

            [
                'id' => 32,
                'pg_id' => 8,
                'name' => '寶可夢 劍',
                'name_jp' => 'ポケットモンスター ソード',
                'description' => '2019年11月15日全球同步發售。',
                'sort' => 32,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 33,
                'pg_id' => 8,
                'name' => '寶可夢 盾',
                'name_jp' => 'ポケットモンスター シールド',
                'description' => '2019年11月15日全球同步發售。',
                'sort' => 33,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 34,
                'pg_id' => 8,
                'name' => '寶可夢 劍 擴充票',
                'name_jp' => 'ポケットモンスター ソード DLC',
                'description' => '系列首次推出付費下載內容（DLC），分為「鎧之孤島」和「冠之雪原」兩個內容，「鎧之孤島」於2020年6月17日推出，「冠之雪原」於2020年10月23日推出。',
                'sort' => 34,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 35,
                'pg_id' => 8,
                'name' => '寶可夢 盾 擴充票',
                'name_jp' => 'ポケットモンスター シールド DLC',
                'description' => '系列首次推出付費下載內容（DLC），分為「鎧之孤島」和「冠之雪原」兩個內容，「鎧之孤島」於2020年6月17日推出，「冠之雪原」於2020年10月23日推出。',
                'sort' => 35,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 36,
                'pg_id' => 8,
                'name' => '寶可夢 晶燦鑽石',
                'name_jp' => 'ポケットモンスター ブリリアントダイヤモンド',
                'description' => '為鑽石版的重製作，預定於2021年冬季全球發售。',
                'sort' => 36,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 37,
                'pg_id' => 8,
                'name' => '寶可夢 明亮珍珠',
                'name_jp' => 'ポケットモンスター シャイニングパール',
                'description' => '為珍珠版的重製作，預定於2021年冬季全球發售。',
                'sort' => 37,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 38,
                'pg_id' => 8,
                'name' => '寶可夢傳說 阿爾宙斯',
                'name_jp' => 'ポケットモンスター アルセウス）',
                'description' => '背景為古代的神奧地區，預定於2022年初全球發售。',
                'sort' => 38,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
        ]);
    }
}
