<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Pocket03CardDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now_date = date('Y-m-d h:i:s');
        
        DB::table('pocket_card_bomb')->truncate();
        DB::table('pocket_card_bomb')->insert([
            [
                'id' => 1,
                'version' => 'CH',
                'catena' => '太陽&月亮系列',
                'name' => '眾星雲集組合篇',
                'description' => '1盒60張',
                'genre' => 'B',
                'code' => null,
                'sort' => 1,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 2,
                'version' => 'CH',
                'catena' => '太陽&月亮系列',
                'name' => '美夢成真組合篇',
                'description' => '1盒60張',
                'genre' => 'B',
                'code' => null,
                'sort' => 2,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 3,
                'version' => 'CH',
                'catena' => '太陽&月亮系列',
                'name' => '雙倍爆擊',
                'description' => '1盒60張',
                'genre' => 'B',
                'code' => null,
                'sort' => 3,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 4,
                'version' => 'CH',
                'catena' => '太陽&月亮系列',
                'name' => '傳說交鋒',
                'description' => '1盒60張',
                'genre' => 'B',
                'code' => null,
                'sort' => 4,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 5,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '劍&盾',
                'description' => '1盒60張',
                'genre' => 'B',
                'code' => null,
                'sort' => 5,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 6,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '無極力量',
                'description' => '1盒60張',
                'genre' => 'B',
                'code' => null,
                'sort' => 6,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 7,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '搭檔',
                'description' => '1盒60張',
                'genre' => 'B',
                'code' => null,
                'sort' => 7,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 8,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '挑戰',
                'description' => '1盒60張',
                'genre' => 'B',
                'code' => null,
                'sort' => 8,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],

            [
                'id' => 9,
                'version' => 'CH',
                'catena' => '太陽&月亮系列',
                'name' => '眾星雲集組合篇 SET A',
                'description' => '1包7張',
                'genre' => 'C',
                'code' => 'AC1a',
                'sort' => 1,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 10,
                'version' => 'CH',
                'catena' => '太陽&月亮系列',
                'name' => '眾星雲集組合篇 SET B',
                'description' => '1包7張',
                'genre' => 'C',
                'code' => 'AC1b',
                'sort' => 2,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 11,
                'version' => 'CH',
                'catena' => '太陽&月亮系列',
                'name' => '美夢成真組合篇 SET A',
                'description' => '1包7張',
                'genre' => 'C',
                'code' => 'AC2a',
                'sort' => 3,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 12,
                'version' => 'CH',
                'catena' => '太陽&月亮系列',
                'name' => '美夢成真組合篇 SET B',
                'description' => '1包7張',
                'genre' => 'C',
                'code' => 'AC2b',
                'sort' => 4,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 13,
                'version' => 'CH',
                'catena' => '太陽&月亮系列',
                'name' => '雙倍爆擊 SET A',
                'description' => '1包6張',
                'genre' => 'C',
                'code' => 'AS5a',
                'sort' => 5,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 14,
                'version' => 'CH',
                'catena' => '太陽&月亮系列',
                'name' => '雙倍爆擊 SET B',
                'description' => '1包6張',
                'genre' => 'C',
                'code' => 'AS5b',
                'sort' => 6,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 15,
                'version' => 'CH',
                'catena' => '太陽&月亮系列',
                'name' => '傳說交鋒 SET A',
                'description' => '1包6張',
                'genre' => 'C',
                'code' => 'AS6a',
                'sort' => 7,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 16,
                'version' => 'CH',
                'catena' => '太陽&月亮系列',
                'name' => '傳說交鋒 SET B',
                'description' => '1包6張',
                'genre' => 'C',
                'code' => 'AS6b',
                'sort' => 8,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],

            [
                'id' => 17,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '劍&盾 SET A',
                'description' => '1包5張',
                'genre' => 'C',
                'code' => 'SC1a F',
                'sort' => 9,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 18,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '劍&盾 SET B',
                'description' => '1包5張',
                'genre' => 'C',
                'code' => 'SC1b F',
                'sort' => 10,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 19,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '無極力量 SET A ',
                'description' => '1包5張',
                'genre' => 'C',
                'code' => 'SC2a F',
                'sort' => 11,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 20,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '無極力量 SET B',
                'description' => '1包5張',
                'genre' => 'C',
                'code' => 'SC2b F',
                'sort' => 12,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 21,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '驚天伏特攻擊',
                'description' => '1包5張',
                'genre' => 'C',
                'code' => 'S4 F',
                'sort' => 13,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 22,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '閃色明星V',
                'description' => '1包10張',
                'genre' => 'C',
                'code' => 'S4a F',
                'sort' => 14,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 23,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '一擊大師',
                'description' => '1包5張',
                'genre' => 'C',
                'code' => 'S5I F',
                'sort' => 15,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 24,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '連擊大師',
                'description' => '1包5張',
                'genre' => 'C',
                'code' => 'S5R F',
                'sort' => 16,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 25,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '歡天喜地組合',
                'description' => '卡牌鑰使圈+5張宣傳卡牌+擴充包一擊大師及擴充包連擊大師各3包',
                'genre' => 'G',
                'code' => null,
                'sort' => 17,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 26,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '頂級強化箱',
                'description' => '擴充包一擊大師及擴充包連擊大師各12包+卡牌 121張+硬幣 2枚+卡牌收納箱 1個+卡牌收納盒 1個+牌組卡套 1套',
                'genre' => 'G',
                'code' => null,
                'sort' => 18,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 27,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '雙璧戰士',
                'description' => '1包5張',
                'genre' => 'C',
                'code' => 'S5a F',
                'sort' => 19,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 28,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '銀白戰槍',
                'description' => '1包5張',
                'genre' => 'C',
                'code' => 'S6H F',
                'sort' => 20,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 29,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '漆黑幽魂',
                'description' => '1包5張',
                'genre' => 'C',
                'code' => 'S6K F',
                'sort' => 21,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 30,
                'version' => 'CH',
                'catena' => '劍&盾系列',
                'name' => '伊布英雄',
                'description' => '1包5張',
                'genre' => 'C',
                'code' => 'S6a F',
                'sort' => 22,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
        ]);

        DB::table('pocket_card_type')->truncate();
        DB::table('pocket_card_type')->insert([
            [
                'id' => 1,
                'name' => '寶可夢卡',
                'description' => '寶可夢卡為遊戲基本用卡，而寶可夢卡又分為基礎寶可夢及進化寶可夢。玩家在開局進行遊戲時只能使用基礎卡。遊戲時，每名玩家只可有一隻戰鬥寶可夢及5隻備戰寶可夢（某些寶可夢的特性可以增加備戰區寶可夢數量，如無極汰那Vmax）。',
                'sort' => 1,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 2,
                'name' => '能量卡',
                'description' => '能量卡為寶可夢提供攻擊時所需的能量。能量卡分為基本能量卡及特殊能量卡兩種。當中基本能量分為十種：草（Grass）、火（Fire）、水（Water）、雷（Lightning）、超能力（Psychic）、鬥（Fighting）、惡（Darkness）、鋼（Metal）、龍（Dragon）。惡與鋼的基本能量卡於「Diamond and Pearl」系列推出，在此之前只有特殊能量卡。龍的基本能量卡在Black & White的「龍之精選」卡包推出。妖精的基本能量卡則於XY才推出。另外，除十種基本能量卡外，遊戲另設有無色（Colorless）能量，任何一種能量都可以當作無色能量使用。',
                'sort' => 2,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 3,
                'name' => '訓練家卡',
                'description' => '訓練家卡讓玩家可以進行更多支援工作，例如回復HP，將已送到棄牌堆的卡回到手牌或牌組等。訓練家卡（Trainer）分為支援者卡（Supporter）、道具卡（Item）、競技場卡（Stadium）。',
                'sort' => 3,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
        ]);

        DB::table('pocket_card_attributes')->truncate();
        DB::table('pocket_card_attributes')->insert([
            [
                'id' => 1,
                'name' => '無色（Colorless）',
                'description' => '灰色/白色，一般、飛行、龍（在龍屬性推出前）',
                'sort' => 1,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 2,
                'name' => '火（Fire）',
                'description' => '紅色，火',
                'sort' => 2,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 3,
                'name' => '水（Water）',
                'description' => '藍色，水、冰',
                'sort' => 3,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 4,
                'name' => '草（Grass）',
                'description' => '綠色，草、蟲、毒（在Diamond & Pearl之前）',
                'sort' => 4,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 5,
                'name' => '電（Lightning）',
                'description' => '黃色，電',
                'sort' => 5,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 6,
                'name' => '格鬥（Fighting）',
                'description' => '橙色，格鬥、岩石、地面',
                'sort' => 6,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 7,
                'name' => '鋼（Metal）',
                'description' => '銀色，鋼',
                'sort' => 7,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 8,
                'name' => '超能力（Psychic）',
                'description' => '紫色，超能力、幽靈、毒（劍盾之前）、妖精（XY之前,劍盾之後）',
                'sort' => 8,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 9,
                'name' => '惡（Darkness）',
                'description' => '黑色，惡、毒（劍盾之後）',
                'sort' => 9,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 10,
                'name' => '龍（Dragon）',
                'description' => '金色，龍（劍盾版本併入無）',
                'sort' => 10,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
            [
                'id' => 11,
                'name' => '妖精（Fairy）',
                'description' => '粉色，妖精（劍盾版本併入超能力）',
                'sort' => 11,
                'status' => 1,
                'created_at' => $now_date,
                'updated_at' => $now_date,
            ],
        ]);
    }
}
